### ISSUE TITLE
[Device] We need a resume event, fired when app comes up from the background

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/wrapper#101]
When an app runs in the background -- when you go back to it we need a resume event -- this is necessary on ios (maybe also on android) to force reconnect the websocket connection

**Comment by michielibiza** [comment]
@shawninder I now send these events through the receive callback, is that how you want 'em?

**Comment by shawninder** [comment]
@michielibiza Yeah that's perfect

**Comment by ninjatux** [comment]
covered in #149 so closing this one
