### ISSUE TITLE
[Amazon Fire] Minimum Specifications/Requirements for the Developer Apps

### ISSUE THREAD

**Issue by gideonvd** [vigour-io/wrapper#106]
Viacom sent us the following:
#### Minimum Specifications/Requirements

1 - Developer to deliver to Amazon the Developer Apps as an Android-based application for access to Developer content optimized for: Amazon Appstore for Android; Fire TV and Fire TV Streaming Stick (the “Fire TV Products”); and Fire tablets (excluding the first generation Fire tablets).

2 - The Developer Apps UI must be rendered in no less than 720p resolution and displayed in a 16:9 aspect ratio.

3 - The Developer Apps must support High-Definition (HD) video playback (no less than 720p).

4 - The Developer Apps must support the defined remote control functionality of Fire TV Products.

5 - The Developer Apps must implement Amazon’s In-App Purchasing API (to the extent that Developer makes In-App Products available for purchase within the Developer Apps).

6 - The Developer Apps (and Developer APIs) will adhere to the following (as may be updated from time to time by Amazon): the Amazon Fire TV and Amazon Fire tablet SDKs (where applicable) and other Program Policies made available within our Mobile App Distribution Portal.

7 - Developer shall provide Amazon with test accounts as needed and test cases for Amazon to test the Developer Apps and Developer APIs.  Developer also will conduct its own tests and certification for the Developer Apps. 

8 - Developer must develop and build the Developer Apps (1) to be compatible with the closed captioning capabilities of the video player used to play content and (2) that has, within the Developer Apps, the closed captioning capabilities set forth under 47 CFR Section 79.103.  The Developer Apps shall comply with applicable closed captioning and emergency information laws and regulations.

9 - The Developer Apps will support launcher integration API from the application launcher to the Developer Apps (e.g., deep-link into application) as documented in the SDK.

10 - Developer will deliver to Amazon an API or data feed in a format acceptable to Amazon so that Amazon can (1) ingest and aggregate such catalog to enable the Amazon Product to search the Developer App’s library of content and (2) determine customer subscriber status to aid the customer experience of signing up new subscribers, authentication, playback options, etc. Such API or data feed will be considered Product Information for purposes of the Agreement.

11 - Without limiting the generality of the foregoing, the Developer Apps shall include the following features:

Fire TV Products:
- Amazon In-App Purchasing API for sale of In-App Products (e.g., for the sale of subscriptions to enable the end user to access premium content).
- Support for the following products (minimum): Fire TV (2014), Fire TV Stick, Amazon Fire TV (2015).

Android devices/Fire tablets:
- Amazon In-App Purchasing API for sale of In-App Products (e.g., for the sale of subscriptions to enable the end user to access premium content).
-  End user can consume all content (including premium content) offline on the device. (This is still under review.)
- Support for the following products (minimum): Gen7 Tablets (2014), Fire HD 6 (2014), Fire HD 7 (2014), Fire HDX 8.9 WAN (2014), Fire HDX 8.9 (2014). Gen8 Tablets (2015), Fire HD 10 (2015), Fire HD 8 (2015), Fire (2015)

**Comment by renancarvalho** [comment]
Hey guys! 
I did some tests with Amazon fire tv, and it is pretty simple. We have two ways of publishing the app:
1 - App Url - We provide an url with the app running
2 - Package App - We provide a zip file with the app.

Amazon give us a simple platform for testing the app locally and a "pre-production" environment. Both following the same way of publishing(url or zip file). The cool thing about the "pre-production" testing, is that we can select testers(users). To publish the app we need to create a developer account and follow these instructions https://developer.amazon.com/public/solutions/platforms/webapps/docs/submitting.html.

Related to the subscription, they also provide an API called "IAP" that allows have subscriptions.(I'll come  with more info about it soon)

I'm still doing a research on it but so far it looks easy to build(vigour-native stuff), test and publish an app.

**Comment by renancarvalho** [comment]
Related to Item 8.
I did not find closed captioning functionalities on Amazon's SDK. I think that if we want to support it, we will need to do it manually. I found this site https://www.law.cornell.edu/cfr/text/47/79.103 that explains these expectations about CC.

**Comment by renancarvalho** [comment]
I'm not sure what item 10 means. do you guys have an Idea ?

**Comment by renancarvalho** [comment]
About item 9 I found this https://developer.amazon.com/public/solutions/devices/fire-tv/docs/catalog/launcher-integration

This is basically, the (Android) integration documentation. I didn't find the HTML API for this.

@youzi seems that some requirements are only available if we do an Android APP.

**Comment by gideonvd** [comment]
@renancarvalho 

Regarding point 8:
- We only have hardcoded subs in MTV Play. Please ignore.

Regarding point 10:
- I think this is something VIMN has to do. I will check with them.
