### ISSUE TITLE
[Plugins] API features

### ISSUE THREAD

**Issue by marcusbesjes** [vigour-io/wrapper#107]
# Native Plugin APIs Feature list

Call out anything missing!
## pay (Purchasing)
- buying store items
  - one off paypment
  - subscriptions (monthly, yearly)
- check if item is purchased
- get info (products, prices) by store account
## auth (login)
- log in (through native app) 
  - with
    - facebook
- log out
##### init()

The init function on the receiver should ensure the sessionId of the session with the sender is set to it's hub client.
## Sharing
- open native share dialog with default text (containing url to share)
- facebook
  - share to a wall
    - friends wall
    - own wall
- email
## status-bar
- set the foreground and background colours, opacity and the status bar display (top, overlay, hidden)
- Same for menu bar on android
## env
- device type (phone/tablet/tv/pc)
- device name (iPhone 6s/Samsung TV)
- device nick (Marcus' iPhone)
- OS (iOS/Android)
  - name
  - version
- bundle id
## network
- network type (WiFi/3G/4G/none)
## orientation
- orientation (portrait/landscape)
## infonline
- see https://github.com/vigour-io/mtv-play/issues/145
## Freezer box

These things are not part of Jan MileStone:

**Comment by marcusbesjes** [comment]
@shawninder: I changed the ChromeCast thing to a note. The problem is basically this: There's two lists of devices: 
1. Other Hub Clients that are logged in as the same user ("Siblings")
2. ChromeCast devices in the vicinity

This is fine until a CC starts casting the app, because then it will be in lists 1 and 2 both.

We know that a device is a CC, but we don't know which ones of list 2 the sibling is, because CC's don't know their own ID for some reason.

The current solution is to just stop showing CC's from list 2 once you see a CC in list 1. This works fine for a single CC, but not for multiple.

**Comment by shawninder** [comment]
@marcusbesjes Does the sending app know the ID's of the CC devices in the viscinity? If so, it could inform each CC of its own ID...

**Comment by marcusbesjes** [comment]
@shawninder We now have a solution for this, by writing the session ID into the hub client on the receiver, we can then set the device ID in the hub client on the sender.

This way we don't have to implement direct communication to the receiver

**Comment by youzi** [comment]
@vigour-io/native Little note on the sharing: Preferably I'd like to be able to create my own dialog from which I would send the necessary info to the bridge. This goes for any plugin btw: when we have the option of making our own dialog that is preferred over showing a native (uncustomizable) dialog.

**Comment by shawninder** [comment]
@youzi Are you sure? This sharing dialog is what people are used to. It's the same when you share a photo from your camera app. Also, it's not that easy a thing to do. The apps can register themselves as share-capable with the OS. I'm not even sure we have access to that info from within our apps. Would be a privacy concern if apps could use this to see what other apps you have installed.

**Comment by youzi** [comment]
@shawninder I'm sure we prefer full control on our side of things. If possible ofc. Having completely custom share messages (like in Spotify) or at least a custom list of possible sharing services (such as Youtube, which when clicking a certain service opens the default dialog), is preferred. 

Most importantly I'd like to prevent us from having a generic share button which would include completely irrelevant options, such as "share on dropbox" etc.

Again this is a preference, if it requires unrealistic amounts of work, or is plain impossible, ofc we will have to work with what we have/can do.

**Comment by youzi** [comment]
@shawninder After some consideration I think we should go for the approach Youtube, Quora and many others implement: Which is having a custom list (this is also what we currently have in mtv-play) => Which opens a native dialog. 

@gideonvd What do you think?

**Comment by shawninder** [comment]
I respectfully disagree :) We're offering to share a plain old link. If people want to share it on dropbox, it's up to them.

But let's look at a more concrete example: I have a lot of friends who don't use facebook for various reasons. It would be quite frustrating to them to see that we support facebook, but not their social media of choice (linkedin, diaspora, app.net, etc.). Unless there's a way for us to get a list of share-capable apps installed on the device (which I doubt), I think I would prefer letting the OS take care of it. Or at the very least, we could have an `other` option to cover those cases.

**Comment by gideonvd** [comment]
I'm in favour of having a custom list. This enables us to support any service our client needs to target regardless of weather the user has that app Installed. Our clients will have

**Comment by shawninder** [comment]
@gideonvd How would you feel adding a link to that list which opens the native dialog?

**Comment by gideonvd** [comment]
@shawninder I certainly wouldn't mind the option. However, the list of share services should be flexible. They will differ from client to client and once we reach a more diverse audience even from region to region.

**Comment by youzi** [comment]
I think we can start by providing the native (share list) dialog, as seen in Safari, NOS (dutch app), Photo's etc. I assume this is the easiest/fastest implementation by far. It seems to me as if the native dialog supports our current platforms out of the box (at least on iOS), being FB, Twitter + more (even when I don't have these apps installed).

This will quickly cover our basic needs and can act as a fallback if we are unable to implement the specific share functionality per service in time (which we should avoid!).

Following that, we can proceed with implementing the specific SDK's, when we have completed our other nr.1 priorities on the native side. When these are also complete we can then offer the user a custom list including a "more" option (as seen in Spotify and other apps), which will be the goal.
/cc @shawninder @gideonvd

**Comment by shawninder** [comment]
agreed

**Comment by gideonvd** [comment]
I don't think that's a good idea and it certainly doesn't cover our basic needs. Our goal should be to have a custom flexible share list like we have in mtv play today. If a native dialog is part of this than fine but it is not our starting point.

**Comment by shawninder** [comment]
@gideonvd The native dialog covers all share-capable apps with very little effort. How does that not cover out basic needs? The custom list is way harder/longer to make and its only advantage is custom styling.

**Comment by youzi** [comment]
@shawninder You are right that the native dialog supports the needs of the user, and I think having this as an option is nice for the user. 

However, there are two other factors we are have to account for and @gideonvd is right to point them out:
- We are rebuilding the mtvplay app, for which they expect a similar UI (not redesigned based on our higher ease of implementation)
- The customer needs to be able to select/highlight/promote/remove/prioritise - in short: control - social services, to accommodate their product/marketing strategy.

I think we should end up implementing the FB (included already when doing login stuff?), Twitter SDK + the native dialog (assuming we already have the Mail integration in place). 

Is it that much more work to integrate the Twitter and FB api vs. the native dialog?
/cc @vigour-io/native

**Comment by shawninder** [comment]
Ok I understand. I guess I only care about the users. I generally don't like marketing strategies :p Makes me sick. But I guess you're right.

Anyways, not sure how much more effort it is, since we need to make our own plugin in any case (can't re-use what we have already)

**Comment by shawninder** [comment]
New plugin proposal: a plugin for "app" stuff (not sure what to call it). Would cover the following (this list is inspired from cordova, but I expect it to evolve into something different/better):
- Allows listening to the following events:
 * `background` or `pause`: fired when the app is sent to the background
 * `resume`: fired when the app is resumed (from background)
 * `back`: fired when the back button is tapped (android)
 * `menu`: fired when the menu button is tapped (android)
 * `xButton`: fired when the "x" physical button is pressed, where "x" is one of:
  + `volumeup`
  + `volumedown`
  + `menu`
  + `search`
  + `startCall`
  + `endCall`
- Allows dismissing the splash screen from app code


@marcusbesjes @youzi @avdwerff @michielibiza @vidbina Thoughts?

**Comment by michielibiza** [comment]
yes fine by me, perhaps we can simplify by having just 5 events: `pause`, `resume`,  `button`, `startCall` & `endCall` and the button event has as argument the name of the button.

**Comment by shawninder** [comment]
agreed

**Comment by ninjatux** [comment]
yeah i agree with @michielibiza 5 events are enough
