### ISSUE TITLE
[IOS] Extra manual step for splash screens with xcode 7.1?

### ISSUE THREAD

**Issue by shawninder** [vigour-io/wrapper#121]
It seems we now need to press a "Use Launch Image Assets" button (or something like that) in the general tab in order to let splash screens work. @avdwerff could this be automated? Do you also have this issue?

**Comment by ninjatux** [comment]
updates on this issue? @shawninder @avdwerff ??

**Comment by avdwerff** [comment]
Is that also the case when the image was provided in the package.json?

**Comment by shawninder** [comment]
@avdwerff yes

**Comment by shawninder** [comment]
The exact process is:

- Go to general tab
- In the `App Icons and Launch Image` section, next to `Launch Image Source`, click on `Use Asset Catalog`
- Select `Assets` from the dropdown list that appears
- Click `Migrate`
- The `Use Asset Catalog` button you clicked earlier is now a dropdown
- In that dropdown, select `LaunchImage`

**Comment by tvervest** [comment]
I've updated the template iOS project to use an assets catalog. I've also added an empty `LaunchImage` asset which acts as a placeholder for the generated asset, in turn allowing me to make this the default selected launch image asset and removing the need for any manual changes to a generated project (for as far as resources go).

**Comment by avdwerff** [comment]
The build script needs to be updated as well, because now the script will generate a launch image (with all sizes from a source) 'the wrong way'.

**Comment by shawninder** [comment]
Actually, it looks like this is working just fine.

**Comment by shawninder** [comment]
Ok, I'm getting this problem again....

**Comment by tvervest** [comment]
Could we have accidentally reverted the fix in the patch for #194?

**Comment by shawninder** [comment]
Doesn't look like it no..
