### ISSUE TITLE
[Plugin] Pay

### ISSUE THREAD

**Issue by ninjatux** [vigour-io/wrapper#132]
see vigour-io/pay#1

**Comment by shawninder** [comment]
Are we sure we want a callback for the buy method? Other options would be to return a promise, or to have `buy` emit an event when it's done, which we can listen on.

Apart from that the API looks nice, I just made some [minor](https://github.com/vigour-io/pay/commit/82944ab1914be5d99a21c1a606c0ab82ff7c0cce) [changes](https://github.com/vigour-io/pay/commit/f22048c61c8c376772dec50415b0919cf81a08c4) to the README, correcting the install method (via npm) and specifying that the package in which to configure the plugin is the app's package...

btw @marcusbesjes You comments are not being synced to GitHub...

**Comment by marcusbesjes** [comment]
This is now the main github thread regarding the Pay Plugin

**Comment by marcusbesjes** [comment]
@shawninder, we decided to do all API modules with callbacks vs promises to avoid confusion and uncaught errors.
On the events: We set properties that you can listen on vs firing dedicated events, so you would subscribe to `pay.products.*.owned` to handle changes in ownership of products vs firing `bought` events, this ties in nicely with the rest of the stack of observable stuffs.
