### ISSUE TITLE
[Wrapper] [Events] Spec

### ISSUE THREAD

**Issue by ninjatux** [vigour-io/wrapper#149]
The wrapper should by default propagate the following events:
- `pause` when the application goers in background
- `resume` when comes back 
- `call(data)` when call is started or ended (data -->`'start' || 'end'`)
- `button` when a button is pressed (data --> `'volup' || 'voldown' || 'home' || 'back'`)

We don't need a plugin for this feature, this feature should always be available. We can listen on the bridge for those events.

**Comment by ninjatux** [comment]
@marcusbesjes can you review this?

**Comment by marcusbesjes** [comment]
@ninjatux, looks complete to me, however I think there is a need for a general "going into background" (pause/call(start)) and "resuming from background" (resume/call(stop)). I don't think there is a big need for the call thing in general, so I would suggest only having `pause` and `resume`, which would also fire when a call pauses the app, and when the app resumes from a call.

@youzi could you quickly confirm there is no need for a dedicated `call` event? Just `pause` and `resume`?

**Comment by youzi** [comment]
@ninjatux @marcusbesjes I currently don't see a need for `call`. `pause` and `resume` should be sufficient.

**Comment by ninjatux** [comment]
@youzi @marcusbesjes also button `home` will put the app in background so it's like the `pause` event, i will not check for it

**Comment by ninjatux** [comment]
an do we want a generic `button` event with data like `volup` or `voldown` or we want an event for every button?

I would say a generic `button` event is enough

**Comment by jimdebeer** [comment]
with a type, what are the types?

**Comment by jimdebeer** [comment]
volume-up
volume-down
off
home
back
forward
settings

**Comment by youzi** [comment]
Generic button event with, `vol up`, `vol down` and `back` feels sufficient to me. `Home` and `menu/settings` are claimed by OS, and I dont think `forward` exists?

**Comment by jimdebeer** [comment]
android?

**Comment by ninjatux** [comment]
hmm never heard of `forward` and `menu` was a button in earlier versions of android but I don't know if is it available. @michielibiza any suggestion about this?

**Comment by michielibiza** [comment]
Menu still exists on some older devices, but I don't think so these devices can install android 4. So no, we don't have a hardware menu button. So the list becomes:
- volume-up
- volume-down
- off
- back
I'm not 100% sure I can expose the off button on android by the way.

**Comment by ninjatux** [comment]
ok let me know if we can catch it, i will add a test for that

**Comment by michielibiza** [comment]
@ninjatux about the back button: I now intercept it: so the js side gets a button event for it, but the app no longer uses the default behaviour (which would be to close the app).
The volume button are also send as events but not intercepted: the user can still adjust the volume
