### ISSUE TITLE
webostv build broken

### ISSUE THREAD

**Issue by shawninder** [vigour-io/wrapper#156]
`ares-package: command not found` (see https://github.com/vigour-io/wrapper/blob/develop/lib/builder/webostv/generateIpkFile.js#L11)

@renancarvalho Looks like I'm missing a dependency. Did you document this anywhere?

**Comment by renancarvalho** [comment]
Yeah man, it is on the readme file, but basically we need to install the SDK manually once it is not available in npm. :( really annoying.
