### ISSUE TITLE
Build Platforms priorities

### ISSUE THREAD

**Issue by renancarvalho** [vigour-io/wrapper#158]
What are our priorities for building scripts (TV's) ?
We already have LG, samsung(excluding Tizen that we still need to test on a real device) and Chromecast.
I know that we still have to create the Roku, Amazon(table, fire tv and stick) and apple tv. 

Based on what we decide here, I'll start to organize my backlog and priorities.

@ninjatux, @shawninder.

**Comment by jimdebeer** [comment]
amazon is #1 (table, fire tv and stick) this is a promise we did to mtv
#2 apple tv (its easier then roku)
#3 (after feb) roku

**Comment by renancarvalho** [comment]
Sweet!  Thanks @jimdebeer

**Comment by jimdebeer** [comment]
btw roku will be a tat weird to do, we need to create a bright script
(visual basic) render engine - so lot more work but very nice when were done

**Comment by renancarvalho** [comment]
yeah, I'll try to understand better about Roku and pass more information to @krystanhuberts. He need's better info about this device.
