### ISSUE TITLE
[Plugins] bridgeReady "event"

### ISSUE THREAD

**Issue by marcusbesjes** [vigour-io/wrapper#168]
Problem: Native Plugins can try to call window.bridge.ready before bridge is required i.e. defined on the window.

Solution:
When JS side bridge is initialised, and exists on the window, it will perform 

``` javascript
bridge.platform.emit('bridgeReady')
```

ios looks something like:

``` javascript
window.NativeInterface.send(stringify( [0, '', 'bridgeReady', '']  ))
```

https://github.com/vigour-io/wrapper/blob/feature/bridgeReady/lib/bridge/ios/index.js#L26

android looks something like:

``` javascript
window.webkit.messageHandlers.vigourBridgeHandler.postMessage({event: 'bridgeReady'})
```

https://github.com/vigour-io/wrapper/blob/feature/bridgeReady/lib/bridge/android/index.js#L39

Each platform has the responsibility to 
- Have a top level "ready" handler on the native side (readyHandler). 
  - In stead of calling window.bridge.ready, plugins will call the readyHandler
  - readyHandler should also be listening for the `bridgeReady` event coming from JS
- on native Plugin.ready > readyHandler should check if `bridgeReady` has occurred
  - if not, store the plugin in a list (readyPlugins)
  - if it has, just forward the call to window.bridge.ready
- when `bridgeReady` event occurs, readyHandler should check the readyPlugins list, and perform the window.bridge.ready calls for them.

@avdwerff @michielibiza 
@shawninder @youzi @ninjatux

**Comment by shawninder** [comment]
Not sure I understand. Don't the plugins require the bridge in order to call its methods?

**Comment by shawninder** [comment]
Never mind, Alex explained it to me :)
