### ISSUE TITLE
[Plugins] plugin register keys / names

### ISSUE THREAD

**Issue by marcusbesjes** [vigour-io/wrapper#169]
We have assumed for a while that a plugin should register with it's package name, however, this would result in ugly API for the devs (our users):

``` JSON
{
  "name": "super-app",
  "vigour": {
    "vigour-facebook": { },
    "vigour-chromecast": { },
    "vigour-pay": { }
  }
}
```

etc.

therefore, from now on we recognise the following _namespaces_ or _scopes_:
- `vigour-`
- `@vigour/`
  (we now use `vigour-`, but should be using `@vigour/`)

This means that, to establish the key by which a plugin should register, we strip either of these scopes from the package name (if applicable), and take whats left as the key/name.

`vigour-facebook` > `facebook`
`@vigour/facebook` > `facebook`
`vigour-chromecast` > `chromecast`

etc.

I wrote a bit of javascript to get the names:

``` javascript
var VNAME = /vigour-(.+)|@vigour\/(.+)/
function parseName (pkgName) {
  var vigourName = pkgName && pkgName.match(VNAME)
  vigourName = vigourName
    ? vigourName[1]
    : pkgName

  if (vigourName) {
    return vigourName
  } else {
    throw Error('could not read package name!')
  }
}
```

@michielibiza @avdwerff you guys will have to do something similar to `getName` on the native side.

@youzi @ninjatux this is something shared by all plugins, so can be part of the new Plugin Class.

**Comment by shawninder** [comment]
@michielibiza @avdwerff I think we can just do this transformation with this function in the js build stuff and you won't need to do the transform on the native side

/cc @marcusbesjes

**Comment by shawninder** [comment]
@marcusbesjes Where are you going to put this function so we can use it across repos? Somewhere in wrapper would be fine because all plugins have a dependency on wrapper anyways...
