### ISSUE TITLE
[Plugins] bridge.receive refactor (emitting events from native to JS)

### ISSUE THREAD

**Issue by marcusbesjes** [vigour-io/wrapper#171]
`bridge.receive(err, message, pluginId)` >> `bridge.receive(event, data, pluginId)`

e.g.
`bridge.receive('pause')`
`bridge.receive('deviceJoined', {id: X}, 'chromecast')`

**Comment by marcusbesjes** [comment]
@ninjatux @shawninder @avdwerff @michielibiza

**Comment by michielibiza** [comment]
And then we can also remove the `bridge.error` call: the native side can just call `bridge.receive('error', '<message>', '<pluginId>')`

**Comment by shawninder** [comment]
The purpose of `receive` is still to pass messages (not errors) from the native side to js.

Examples:

- **native events** `bridge.receive(event)
- `bridge.receive('pause')`
- `bridge.receive('resume')`
- **plugin events** `bridge.receive(event, data, pluginId)
- `bridge.receive('deviceJoined', { id: 'X' }, 'chromecast')

**Comment by michielibiza** [comment]
We just removed the error function so indeed: `bridge.receive('error', 'invalid key', 'facebook')` in stead of `bridge.error('invalid key', 'facebook')`

**Comment by shawninder** [comment]
I updated my above comment to give examples of error events
