### ISSUE TITLE
Fix web view User-Agent strings

### ISSUE THREAD

**Issue by shawninder** [vigour-io/wrapper#188]
When the webviews makes an http or https request to get the html of the app, or any other resource, the request is always sent along with headers, one of them being the "User-Agent" header, which describes the user-agent/browser, in this case the web view.

Unfortunately, the default User-Agent strings used by our webviews are currently not sufficient to allow the packer to differentiate between a native app and a browser on a phone or tablet. Fortunately, the [standard being developed for this](http://tools.ietf.org/html/rfc7231#section-5.5.3) is flexible enough to allow us to add extra info in the User-Agent header. Let's keep the same User-Agent string the webviews have by default, but add two keywords at the end.

1. `vigour-wrapper` (this means we are native, not just a browser)
2. `phone` or `tablet` (not only we are native, but we correspond to a device category. For phablets, use `tablet`)

@avdwerff @michielibiza @tvervest @marcusbesjes

**Comment by shawninder** [comment]
For example, if the default User-Agent string for the webview is `Galaxy/1.0 [en] (Mac OS X 10.5.6; U; en)`, then you should change it to `Galaxy/1.0 [en] (Mac OS X 10.5.6; U; en) vigour-wrapper phone` or `Galaxy/1.0 [en] (Mac OS X 10.5.6; U; en) vigour-wrapper tablet`

**Comment by avdwerff** [comment]
done.

**Comment by shawninder** [comment]
This is now done on Android as well, closing
