### ISSUE TITLE
[Dependencies] Install dependencies automatically

### ISSUE THREAD

**Issue by shawninder** [vigour-io/wrapper#19]
The first time you run a build for a specific platform, the build script should install everything needed for that platform automatically. This means SDKs, build tools, Java, Ruby, whatever is needed!

### main objective

A freshly installed computer with nothing but git, node and npm should be able to build for native with the following, nothing more:

```
git clone <project>
npm install
npm run build -- ios android
```

### notes

- The first time building for a new platform will be super long, so also include a message for the user explaining why it's so long and that subsequent builds will be much faster.
- I don't want to install these dependencies via npm because that would install all dependencies for every project, whereas I expect most projects will only support a few platforms. So for example, if you don't support Android, you don't want to waste time installing all the android SDKs on `npm install`..
- Ideally we can make this work on any OS for most platforms, but building for Windows Phone needs Visual Studio and iOS needs xcode, so we may have to fall back on a message to the user: "please try again on a windows machine"... OR we can provide a (paid) service that makes the builds for you with online machines of every kind (mac, windows)...

**Comment by ninjatux** [comment]
don't know if this is a good feature to have. we should instead document the process of installing extra dependencies otherwise every `npm install vigour-wrapper` will trigger a hell of a job!

anyway closing for the sake of having a clean issue log, we can get it back later if needed.

**Comment by shawninder** [comment]
yeah we need a way to install automatically only if it's not already installed. But I do think `npm install` should install everything needed as much as possible. As you said though, this is quite a low priority.
