### ISSUE TITLE
[android] Errors on startup

### ISSUE THREAD

**Issue by youzi** [vigour-io/wrapper#191]
Not sure who to assign, but I'm getting lots of errors on start up on android using the app-tester.
![image](https://cloud.githubusercontent.com/assets/5662898/13378976/96b352d0-de18-11e5-80d3-ffca1e681c77.png)
/cc @michielibiza @marcusbesjes

**Comment by shawninder** [comment]
@youzi If you're expecting plugins to work with app-tester, they don't. I think this might be related to what we were discussing the other day. Remember I was telling you I had an ungly temporary solution for this?

**Comment by shawninder** [comment]
wrapper is pretty much obsolete
