### ISSUE TITLE
[wrapper] wrapping for iOS complains of purchase things

### ISSUE THREAD

**Issue by marcusbesjes** [vigour-io/wrapper#197]
When wrapping for iOS (in a project that does not include the pay plugin), building fails because of the following errors:

![image](https://cloud.githubusercontent.com/assets/3897729/14350873/4686bd42-fccc-11e5-8b23-140701719fd5.png)

![image](https://cloud.githubusercontent.com/assets/3897729/14350883/57bf2fae-fccc-11e5-9769-a41f1b8a8ca2.png)

@avdwerff @tvervest could you guys check this out? I'm going to check if I am able to build with older versions of the wrapper.

**Comment by marcusbesjes** [comment]
I tried commenting all purchase things, but now I get 
![image](https://cloud.githubusercontent.com/assets/3897729/14351388/45571842-fccf-11e5-98ad-61e5048674fe.png)

**Comment by avdwerff** [comment]
It is because of the latest swift and xcode, changes in the API for payment. So either you use the previous xcode version (downloadable from apple dev), update the project from the repo (I did fix this yesterday) and build without cocoapods or... remove the pay.swift file.

**Comment by avdwerff** [comment]
...if removing do not forget to remove the register class code line in the application delegate

**Comment by marcusbesjes** [comment]
so if we publish a new version of vigour-wrapper this is fixed?

**Comment by avdwerff** [comment]
jep.

> On 07 Apr 2016, at 14:51, Marcus Besjes <notifications@github.com> wrote:
> 
> so if we publish a new version of vigour-wrapper this is fixed?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub <https://github.com/vigour-io/wrapper/issues/197#issuecomment-206877567>

Met vriendelijke groet,
Alexander van der Werff

WERFF Consultancy & Development

p: +31(0)6 20 411 032
e: avdwerff@gmail.com
s: www.alexandervanderwerff.com/ <http://www.alexandervanderwerff.com/>

Bob Billy
s: bobbilly.com/ <http://bobbilly.com/>
s: soundcloud.com/bob-billy <http://soundcloud.com/bob-billy>

WERFFMEISTER
s: soundcloud.com/werffmeister <https://soundcloud.com/werffmeister>

**Comment by marcusbesjes** [comment]
after publishing the latest code from develop to master to npm:

![image](https://cloud.githubusercontent.com/assets/3897729/14354858/34173138-fcdf-11e5-9ca1-7437fc75e426.png)

**Comment by avdwerff** [comment]
but the pod repo should be updated, so an official release, version bump etc. ..what did you do?

**Comment by marcusbesjes** [comment]
I merged develop (where I saw your latest update) into master and published to npm vigour-wrapper@4.0.7

**Comment by avdwerff** [comment]
check if the pod statement is in the pod file, npm publishing wont publish the latest cocoapod spec update to the pod repo... the pod spec checks a tag (release), so the spec should be udated or for now use pod statement I added in the previous comment.

**Comment by marcusbesjes** [comment]
ok I can build now by manually adding 

```
pod 'VigourCore', :git => 'https://github.com/vigour-io/wrapper.git', :branch => 'develop'
```

to the `Podfile` file in the generated `/build/ios/vigour-native/` directory, and running `pod install`.

Thanks for the quick response @avdwerff , now I'm wondering how this came about and how we will fix it for real.

**Comment by marcusbesjes** [comment]
Seems to me the generated `Podfile` is just missing that line?
