### ISSUE TITLE
webkitShowPlaybackTargetPicker doesn't list available devices

### ISSUE THREAD

**Issue by ricksmit3000** [vigour-io/wrapper#201]
Since iOS 7, Safari allows you to show custom controls (basically your own Airplay button) when an Apple TV is available. You do so by listening on the `window.WebKitPlaybackTargetAvailabilityEvent`

The latest reference on the [Airplay developers website](https://developer.apple.com/airplay/) about the iOS Airplay API, still lists this as an available function:

<img width="1628" alt="screen shot 2016-04-29 at 17 00 11" src="https://cloud.githubusercontent.com/assets/7207783/14920083/1400b35c-0e2c-11e6-8ff0-c79dc9ccd26e.png">

Although I'm able to detect that there is an Apple TV available, I'm unable to get the Device Target picker dialog to list the devices with `webkitShowPlaybackTargetPicker()`. All it shows is an empty dialog when I click my custom Airplay button.

**Systems affected:**
- iOS Native
- iOS Mobile web

When I logged the `WebKitPlaybackTargetAvailabilityEvent` in Safari Technology Preview, I did notice that there were some additional event properties, which might indicate that this would be fixed in a newer version of Safari but I'm unable to test that at the moment.

I've raised this issue on the [webkit issue](https://bugs.webkit.org/show_bug.cgi?id=157173) tracking system, awaiting a reply. Alternatively, maybe we could use this native code to display an Airplay button @avdwerff? 

``` swift
MPVolumeView *volumeView = [[MPVolumeView alloc] init];
[volumeView setShowsVolumeSlider:NO];
[volumeView sizeToFit];
[view addSubview:volumeView];
```

From what I've learned from this W3C Remote Playback [discussion](https://github.com/w3c/remote-playback/issues/1), is that most websites only use the Airplay API for enabling/disabling the Airplay button. 

If you'd like to check out an example implementation and see what we have so far, you can clone the `vigour-player` repo on the [feature/airplay](https://github.com/vigour-io/player/tree/feature/airplay) branch.

**Working:**
- Enable/Disable Airplay button (Native & Web).
- Stream video from Mac OS (El Capitan) with Safari 9.

cc @youzi

**Comment by avdwerff** [comment]
Hi, is this still a valid issue? Since I learned Vigour is going to use Cordova for wrapping.. @rickiesmooth

**Comment by marcusbesjes** [comment]
@avdwerff you are right, @rickiesmooth We are building a Cordova plugin right now to detect, and cast videos to, Airplay and ChromeCast devices: https://github.com/vigour-io/cast.

**Comment by ricksmit3000** [comment]
@marcusbesjes From the [airplay developer docs:](https://developer.apple.com/library/ios/documentation/AudioVideo/Conceptual/AirPlayGuide/EnrichYourAppforAirPlay/EnrichYourAppforAirPlay.html#//apple_ref/doc/uid/TP40011045-CH6-SW3)

If your app plays media, you might want to provide an AirPlay output picker within your app so that the user doesn’t have to change focus. You can add an AirPlay picker to your media playback controls by using `MPVolumeView`, as shown in the following code snippet:

```
MPVolumeView *volumeView = [ [MPVolumeView alloc] init] ;
[view addSubview:volumeView];
```

If you have a custom media controller and don’t want to use the standard volume controller, you can add just the AirPlay picker using the following code snippet:

```
MPVolumeView *volumeView = [ [MPVolumeView alloc] init] ;
[volumeView setShowsVolumeSlider:NO];
[volumeView sizeToFit];
[view addSubview:volumeView];
```

The picker is visible only when there is an AirPlay output device available.
