### ISSUE TITLE
[Wrapper] [Device] Spec device informations

### ISSUE THREAD

**Issue by shawninder** [vigour-io/wrapper#31]
Apps will want to have access to certain information:
- plaform
- device
- build info
  + bundle id / app id
- more...

We have to decide what the best way to achieve this is. Perhaps something like
```
window.env = {
  platform: 'ios 9.0',
  device: 'Apple iPhone 5s',
  bundleId: 'io.vigour.awesome'
  version: '1.2.3'
}
```

**Comment by ninjatux** [comment]
from the discussion opened in #49 

Would be nice to have an `Observable` object attached to `window.vigour.device which provides various informations about the device itself, eg: **uuid**, **ad-id**, **platform** and so on.

We should have the specs defined in this issue.

**Comment by youzi** [comment]
Is window.vigour.device the same as 'env'?

**Comment by shawninder** [comment]
@ninjatux I think these specs should be defined in the `env` plugin, which is responsible for this stuff. @youzi so `env` would be the plugin responsible for populating `window.vigour.device`

**Comment by youzi** [comment]
I think @valerio and @shawninder have this covered. Can we close this?

**Comment by ninjatux** [comment]
yep, clsoing
