### ISSUE TITLE
[IOS] Allow building `ipa` programmatically

### ISSUE THREAD

**Issue by shawninder** [vigour-io/wrapper#84]

**Comment by tvervest** [comment]
This should be fairly easy to implement using the [xcodebuild](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/xcodebuild.1.html) command

**Comment by avdwerff** [comment]
Yes, but this task also meant setting the right provisioning and code sign stuff, which van be a bitch, specially when you are assigned as 3'rd party dev like with the MTV project. All doable but I think we can better use some tools from Fastlane; a collection of iOS app continuous deployment and integration tools.

**Comment by tvervest** [comment]
Agreed, the compiling won't be much of an issue (that is, as soon as all the auto-include code works for plugins), but certificates remain an issue that `cert` could solve. Just to clarify (and record) how this works, are apps generally released using an existing signing certificate (for example from previous apps), or do you create new certificates for the client?

**Comment by avdwerff** [comment]
All clients have their own Apple account and so they need to add Vigour as 3rd party dev to their team.

**Comment by shawninder** [comment]
We use the same certificate everywhere nowadays as far as I know. Notable exception: I think the live MTV production app uses a certificate created by the people at VIACOM.. But these are demo and prototype times.. When we ship more real apps, we'll need to figure out how to better organize all this certificate and provisioning profile hell. According to the fine people at Apple, there is no one correct way to do this, every case is different, etc. But the perfect solution is often impossible because there are all sorts of restrictions, like a maximum number of certificates and other idiocies. We have to think of the right way to handle this crap on the long run, and automate as much as possible. In the end, what we want is to completely ignore all that bullshit and have it all handled by the build script automatically. Not only because it's poorly designed, takes a lot of time, and changes nothing for the app itself, but also because it's platform-specific.

**Comment by avdwerff** [comment]
Well maybe there is 1 client now, in the future they will have all their own account. The way it should be.

**Comment by avdwerff** [comment]
The clients can make us technical admins, so we can adjust prov profiles, if not it is a nice treat for PM's to get updated certificates.
