### ISSUE TITLE
[Plugin] Plugin names

### ISSUE THREAD

**Issue by shawninder** [vigour-io/wrapper#86]
In this issue, I'd like to decide what the names of all plugins will be and their respective priority.

We should be able to find each plugin at `github.com/vigour-io/<name>`

| priority | name | other possible names | description & scope |
| --- | --- | --- | --- |
| 1 | status-bar | bars | native status bar control (and the menu bar on android) |
| 1 | env | environment, info, device, device-info, platform, client | provides static info about the device and platform's name and version, bundle id, etc. |
| 1 | network | connectivity | provides an observable for connectivity (wifi, 3G, 4G, none, etc.) |
| 1 | orientation |  | listens to the orientation of the device (pure js?) |
| 1 | pay | purchasing, money, payment, store, purchase | native purchasing and plugin architecture for web payments (pay pal, credit card, ...) |
| 1 | auth | login | login via facebook, google +, others |
| 1 | chromecast |  | Everything needed for Chromecast sender apps |
| 1 | share |  | Share via other apps (e-mail, facebook, twitter, google +, etc.). |
| 1 | infonline |  | InfOpen stuff |
| 2 | dial |  | everything DIAL |
| 3 | notify |  | native notifications |
| 3 | remote |  | Remote controls |
| 4 | fs |  | Native file system access including file transfer (upload/download) |
| 4 | settings | user-settings | Observable for device settings, e.g. preferred language, date & time format, etc. |

For now, let's just agree on a name & priority for each plugin. The scope of each plugin is way bigger than what we need immediately, and prioritizing specific features will happen in that plugin's repo. For example, we won't care about the user's preferred date & time format for a very long time, but that plugin is indeed a # 1 priority because we will be interested in connectivity.

I'm not particularly attached to any of these names, so please propose alternatives for all of them. I'd like to have all these names settled by Sunday morning (no beating around the bush).

/cc @jimdebeer @youzi @gideonvd

**Comment by marcusbesjes** [comment]
@jimdebeer We discussed the following changes:

- create a facebook plugin with
  - facebook.share
  - facebook.login

- demote "share" plugin priority

- remove "auth" plugin

**Comment by shawninder** [comment]
I don't like it.

Devices have this general share thing where you share stuff and they propose a list of all the share-capable apps on your device (whatsapp, slack, mail, hipchat, message, iCloud, twitter, save PDF to iBooks, snapchat, messenger, etc, etc, etc). So I don't see why the share feature sould be in the facebook plugin, as you may want to share with other apps, and we don't want one plugin per app (we'll never see the end of it).

Same goes for login. We currently only support logging in via facebook or e-mail, but it's reasonable to think we'll be logging in via oauth, twitter, etc, in the future. Do we really want one plugin per login-capable app?

Of course, my argument is less strong for login, as there is no general login via xyz dialog offered by native devices. But for sharing, this seems quite obvious to me.

**Comment by vidbina** [comment]
About the naming thing... I'd say let's use npm scopes. New NPM has already
cost us quite a bit of extra effort so let's enjoy the perks at least.
https://docs.npmjs.com/getting-started/scoped-packages

**Comment by michielibiza** [comment]
@ninjatux you asked for a rough estimate of the prio 1 plugins:
plugin|estimation|remark
---|---|---
status-bar | 3h | 
env | 1h | 
network connectivity | 3h | 
orientation | 2 | 
pay | 8h | just play store, right? no native sdk for paypall I hope... 
auth | 8h | depends on how many varieties 
chromecast | 8h | never done this before, I don't know... 
share | 8h | also here it depends on what we need as a minimum 
infonline | -- | AFAIK not possible (see comment above)

**Comment by ninjatux** [comment]
@michielibiza  don't forget facebook, it was included later but is needed for a specific implementation so we want to give it max priority

**Comment by shawninder** [comment]
8h for the pay plugin, you are so cute @michielibiza ! I guess you weren't there yet last time we did this, but there was a shitstorm of fuckness sourrounding this whole purchasing stuff: Incorrect documentation, broken test apis, blocked google accounts, lack of control over the actual store account, etc. Plus things have most probably changed considerably since then as well.. I hope you're right about this, but I would advise planning a little more time more this.

The other estimates make sense however :) Thanks

**Comment by michielibiza** [comment]
@shawninder haha, thanks for the feedback :)
I think a lot here is about scope: 8 h for the pay plugin should be enough to get something working on a test account (since I already have something that worked beginning of the year, I think it shouldn't take too long to get that up and running). But indeed that doesn't include debugging play store setup in actual products! 
So I think we can gat a plugin that purchases from a test app in our own play store account. But indeed there is always some nightmarish version/key twiddling for products where we don't have access to the play store that can take days. This however should be part of the planning of the product itself.

Does that make more sense or do you still think 8h is too little?

**Comment by michielibiza** [comment]
@ninjatux So if we pull facebook out of the plugins `auth` and `share` what is left in auth and share (as a minimum requirement)? I think a facebook plugin should take about a day. But perhaps the estimates for auth and share would come down after that.

**Comment by michielibiza** [comment]
Oh and just to make one more thing clear: All my estimates are for the native side only. I'm assuming that  the bridge stuff and the npm dependency shit is all taken care of. Do we need more ideas on how to limit breakage of dependencies given that none of the dependencies are _done_?

Furthermore I might need to do a tiny bit more on the android build process so in total it's about 7 to 8 days
